language: go

go:
  - 1.12.8
  - master

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: "Tests"
      script:
      - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
      - bash <(curl -s https://codecov.io/bash)
    - stage: "Build"
      script:
      - docker build -t travis-ci-build-stages-demo .